version: "3.9"  # optional since v1.27.0
services:
  db:
    ports: 
      - "3306:3306"
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: lab10
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
